----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 2.0.0 Feb. 1, 2011
-- ?? ??? 28 2014 09:46:21
--
--      Input file      : 
--      Component name  : clk_rst_wrapper
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.all;
library UNISIM;
use UNISIM.Vcomponents.all;

ENTITY clk_rst_wrapper IS
   PORT (
      PCIE_REFCLKP      : IN STD_LOGIC;
      PCIE_REFCLKN      : IN STD_LOGIC;
      PERSTN            : IN STD_LOGIC;
      
      sw_reset_n        : IN STD_LOGIC;
      
      pcie_trn_reset_n  : IN STD_LOGIC;
      
      pcie_refclk       : OUT STD_LOGIC;
      
      hw_reset_n        : OUT STD_LOGIC;
      sys_reset_n       : OUT STD_LOGIC
   );
END ENTITY clk_rst_wrapper;

ARCHITECTURE trans OF clk_rst_wrapper IS
   
   -- Declare intermediate signals for referenced outputs
   SIGNAL pcie_refclk_xhdl0 : STD_LOGIC;
BEGIN
   -- Drive referenced outputs
   pcie_refclk <= pcie_refclk_xhdl0;
   
   hw_reset_n <= PERSTN;
   sys_reset_n <= (PERSTN AND sw_reset_n AND pcie_trn_reset_n );
   
   
   
   pcie_refclk_ibuf : IBUFDS
      PORT MAP (
         o   => pcie_refclk_xhdl0,
         i   => PCIE_REFCLKP,
         ib  => PCIE_REFCLKN
      );
   
END ARCHITECTURE trans;






