----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 2.0.0 Feb. 1, 2011
-- ?? ??? 28 2014 09:39:29
--
--      Input file      : 
--      Component name  : pcie_wrapper
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;


entity pcie_wrapper is
  generic (
    tDLY : integer := 0
    );
  port (

    pcie_refclk      : in  std_logic;
    pcie_us_clk      : in  std_logic;
    pcie_ds_clk      : in  std_logic;
    perstn           : in  std_logic;
    sys_reset_n      : in  std_logic;
    pcie_trn_clk     : out std_logic;
    pcie_trn_reset_n : out std_logic;
    trn_lnk_up_n     : out std_logic;

    pci_exp_txp : out std_logic_vector(3 downto 0);
    pci_exp_txn : out std_logic_vector(3 downto 0);
    pci_exp_rxp : in  std_logic_vector(3 downto 0);
    pci_exp_rxn : in  std_logic_vector(3 downto 0);

    b1_w32_w  : out std_logic;
    b1_w32_be : out std_logic_vector(3 downto 0);
    b1_w32_d  : out std_logic_vector(31 downto 0);
    b1_w32_a  : out std_logic_vector(31 downto 0);
    b1_r32_r  : out std_logic;
    b1_r32_be : out std_logic_vector(3 downto 0);
    b1_r32_a  : out std_logic_vector(31 downto 0);
    b1_r32_q  : in  std_logic_vector(31 downto 0);

    sim_error : in std_logic;

    sw_reset_n : out std_logic;

    record_en : out std_logic;
    play_en   : out std_logic;
    sim_en    : out std_logic;

    fifo_wrreq_pcie_us     : in  std_logic;
    fifo_data_pcie_us      : in  std_logic_vector(63 downto 0);
    fifo_prog_full_pcie_us : out std_logic;

    fifo_rdreq_pcie_ds : in  std_logic;
    fifo_q_pcie_ds     : out std_logic_vector(63 downto 0);
    fifo_empty_pcie_ds : out std_logic
    );
end entity pcie_wrapper;

architecture trans of pcie_wrapper is
  constant PCI_EXP_LINK_WIDTH       : integer := 4;
  constant PCI_EXP_TRN_DATA_WIDTH   : integer := 64;
  constant PCI_EXP_TRN_REM_WIDTH    : integer := 8;
  constant PCI_EXP_TRN_BUF_AV_WIDTH : integer := 4;
  constant PCI_EXP_BAR_HIT_WIDTH    : integer := 7;
  constant PCI_EXP_FC_HDR_WIDTH     : integer := 8;
  constant PCI_EXP_FC_DATA_WIDTH    : integer := 12;
  constant PCI_EXP_CFG_DATA_WIDTH   : integer := 32;
  constant PCI_EXP_CFG_ADDR_WIDTH   : integer := 10;
  constant PCI_EXP_CFG_CPLHDR_WIDTH : integer := 48;
  constant PCI_EXP_CFG_BUSNUM_WIDTH : integer := 8;
  constant PCI_EXP_CFG_DEVNUM_WIDTH : integer := 5;
  constant PCI_EXP_CFG_FUNNUM_WIDTH : integer := 3;
  constant PCI_EXP_CFG_CAP_WIDTH    : integer := 16;

  component endpoint_blk_plus_v1_13
    port (
      pci_exp_txp                : out std_logic_vector(PCI_EXP_LINK_WIDTH-1 downto 0);
      pci_exp_txn                : out std_logic_vector(PCI_EXP_LINK_WIDTH-1 downto 0);
      pci_exp_rxp                : in  std_logic_vector(PCI_EXP_LINK_WIDTH-1 downto 0);
      pci_exp_rxn                : in  std_logic_vector(PCI_EXP_LINK_WIDTH-1 downto 0);
      trn_clk                    : out std_logic;
      trn_reset_n                : out std_logic;
      trn_lnk_up_n               : out std_logic;
      trn_td                     : in  std_logic_vector(PCI_EXP_TRN_DATA_WIDTH-1 downto 0);
      trn_trem_n                 : in  std_logic_vector(PCI_EXP_TRN_REM_WIDTH-1 downto 0);
      trn_tsof_n                 : in  std_logic;
      trn_teof_n                 : in  std_logic;
      trn_tsrc_rdy_n             : in  std_logic;
      trn_tdst_rdy_n             : out std_logic;
      trn_tdst_dsc_n             : out std_logic;
      trn_tsrc_dsc_n             : in  std_logic;
      trn_terrfwd_n              : in  std_logic;
      trn_tbuf_av                : out std_logic_vector(PCI_EXP_TRN_BUF_AV_WIDTH-1 downto 0);
      trn_rd                     : out std_logic_vector(PCI_EXP_TRN_DATA_WIDTH-1 downto 0);
      trn_rrem_n                 : out std_logic_vector(PCI_EXP_TRN_REM_WIDTH-1 downto 0);
      trn_rsof_n                 : out std_logic;
      trn_reof_n                 : out std_logic;
      trn_rsrc_rdy_n             : out std_logic;
      trn_rsrc_dsc_n             : out std_logic;
      trn_rdst_rdy_n             : in  std_logic;
      trn_rerrfwd_n              : out std_logic;
      trn_rnp_ok_n               : in  std_logic;
      trn_rbar_hit_n             : out std_logic_vector(PCI_EXP_BAR_HIT_WIDTH-1 downto 0);
      trn_rfc_nph_av             : out std_logic_vector(PCI_EXP_FC_HDR_WIDTH-1 downto 0);
      trn_rfc_npd_av             : out std_logic_vector(PCI_EXP_FC_DATA_WIDTH-1 downto 0);
      trn_rfc_ph_av              : out std_logic_vector(PCI_EXP_FC_HDR_WIDTH-1 downto 0);
      trn_rfc_pd_av              : out std_logic_vector(PCI_EXP_FC_DATA_WIDTH-1 downto 0);
      trn_rcpl_streaming_n       : in  std_logic;
      cfg_do                     : out std_logic_vector(PCI_EXP_CFG_DATA_WIDTH-1 downto 0);
      cfg_rd_wr_done_n           : out std_logic;
      cfg_di                     : in  std_logic_vector(PCI_EXP_CFG_DATA_WIDTH-1 downto 0);
      cfg_byte_en_n              : in  std_logic_vector(PCI_EXP_CFG_DATA_WIDTH/8-1 downto 0);
      cfg_dwaddr                 : in  std_logic_vector(PCI_EXP_CFG_ADDR_WIDTH-1 downto 0);
      cfg_wr_en_n                : in  std_logic;
      cfg_rd_en_n                : in  std_logic;
      cfg_err_cor_n              : in  std_logic;
      cfg_err_ur_n               : in  std_logic;
      cfg_err_ecrc_n             : in  std_logic;
      cfg_err_cpl_timeout_n      : in  std_logic;
      cfg_err_cpl_abort_n        : in  std_logic;
      cfg_err_cpl_unexpect_n     : in  std_logic;
      cfg_err_posted_n           : in  std_logic;
      cfg_err_tlp_cpl_header     : in  std_logic_vector(PCI_EXP_CFG_CPLHDR_WIDTH-1 downto 0);
      cfg_err_cpl_rdy_n          : out std_logic;
      cfg_err_locked_n           : in  std_logic;
      cfg_interrupt_n            : in  std_logic;
      cfg_interrupt_rdy_n        : out std_logic;
      cfg_interrupt_assert_n     : in  std_logic;
      cfg_interrupt_di           : in  std_logic_vector(7 downto 0);
      cfg_interrupt_do           : out std_logic_vector(7 downto 0);
      cfg_interrupt_mmenable     : out std_logic_vector(2 downto 0);
      cfg_interrupt_msienable    : out std_logic;
      cfg_to_turnoff_n           : out std_logic;
      cfg_pm_wake_n              : in  std_logic;
      cfg_pcie_link_state_n      : out std_logic_vector(2 downto 0);
      cfg_trn_pending_n          : in  std_logic;
      cfg_bus_number             : out std_logic_vector(PCI_EXP_CFG_BUSNUM_WIDTH-1 downto 0);
      cfg_device_number          : out std_logic_vector(PCI_EXP_CFG_DEVNUM_WIDTH-1 downto 0);
      cfg_function_number        : out std_logic_vector(PCI_EXP_CFG_FUNNUM_WIDTH-1 downto 0);
      cfg_dsn                    : in  std_logic_vector(63 downto 0);
      cfg_status                 : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      cfg_command                : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      cfg_dstatus                : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      cfg_dcommand               : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      cfg_lstatus                : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      cfg_lcommand               : out std_logic_vector(PCI_EXP_CFG_CAP_WIDTH-1 downto 0);
      fast_train_simulation_only : in  std_logic;
      sys_clk                    : in  std_logic;
      refclkout                  : out std_logic;
      sys_reset_n                : in  std_logic); 
  end component;
  component pcie_dma_wrapper is
    generic (
      tDLY : integer := 0
      );
    port (
      trn_clk                    : in  std_logic;
      pcie_us_clk                : in  std_logic;
      pcie_ds_clk                : in  std_logic;
      trn_reset_n                : in  std_logic;
      trn_lnk_up_n               : in  std_logic;
      sys_reset_n                : in  std_logic;
      trn_tsof_n                 : out std_logic;
      trn_teof_n                 : out std_logic;
      trn_tsrc_rdy_n             : out std_logic;
      trn_tdst_rdy_n             : in  std_logic;
      trn_trem_n                 : out std_logic_vector(7 downto 0);
      trn_td                     : out std_logic_vector(63 downto 0);
      trn_tsrc_dsc_n             : out std_logic;
      trn_tdst_dsc_n             : in  std_logic;
      trn_tbuf_av                : in  std_logic_vector(3 downto 0);
      trn_rsof_n                 : in  std_logic;
      trn_reof_n                 : in  std_logic;
      trn_rsrc_rdy_n             : in  std_logic;
      trn_rdst_rdy_n             : out std_logic;
      trn_rrem_n                 : in  std_logic_vector(7 downto 0);
      trn_rd                     : in  std_logic_vector(63 downto 0);
      trn_rerrfwd_n              : in  std_logic;
      trn_rsrc_dsc_n             : in  std_logic;
      trn_rnp_ok_n               : out std_logic;
      trn_rcpl_streaming_n       : out std_logic;
      trn_rbar_hit_n             : in  std_logic_vector(6 downto 0);
      trn_rfc_ph_av              : in  std_logic_vector(7 downto 0);
      trn_rfc_pd_av              : in  std_logic_vector(11 downto 0);
      trn_rfc_nph_av             : in  std_logic_vector(7 downto 0);
      trn_rfc_npd_av             : in  std_logic_vector(11 downto 0);
      cfg_wr_en_n                : out std_logic;
      cfg_rd_en_n                : out std_logic;
      cfg_rd_wr_done_n           : in  std_logic;
      cfg_byte_en_n              : out std_logic_vector(3 downto 0);
      cfg_dwaddr                 : out std_logic_vector(9 downto 0);
      cfg_di                     : out std_logic_vector(31 downto 0);
      cfg_do                     : in  std_logic_vector(31 downto 0);
      cfg_bus_number             : in  std_logic_vector(7 downto 0);
      cfg_device_number          : in  std_logic_vector(4 downto 0);
      cfg_function_number        : in  std_logic_vector(2 downto 0);
      cfg_status                 : in  std_logic_vector(15 downto 0);
      cfg_command                : in  std_logic_vector(15 downto 0);
      cfg_dstatus                : in  std_logic_vector(15 downto 0);
      cfg_dcommand               : in  std_logic_vector(15 downto 0);
      cfg_lstatus                : in  std_logic_vector(15 downto 0);
      cfg_lcommand               : in  std_logic_vector(15 downto 0);
      cfg_dsn                    : out std_logic_vector(63 downto 0);
      cfg_pm_wake_n              : out std_logic;
      cfg_pcie_link_state_n      : in  std_logic_vector(2 downto 0);
      cfg_to_turnoff_n           : in  std_logic;
      cfg_interrupt_mmenable     : in  std_logic_vector(2 downto 0);
      cfg_interrupt_msienable    : in  std_logic;
      cfg_interrupt_do           : in  std_logic_vector(7 downto 0);
      cfg_interrupt_n            : out std_logic;
      cfg_interrupt_rdy_n        : in  std_logic;
      cfg_interrupt_di           : out std_logic_vector(7 downto 0);
      cfg_interrupt_assert_n     : out std_logic;
      cfg_err_ecrc_n             : out std_logic;
      cfg_err_ur_n               : out std_logic;
      cfg_err_cpl_timeout_n      : out std_logic;
      cfg_err_cpl_unexpect_n     : out std_logic;
      cfg_err_cpl_abort_n        : out std_logic;
      cfg_err_posted_n           : out std_logic;
      cfg_err_cor_n              : out std_logic;
      cfg_err_tlp_cpl_header     : out std_logic_vector(47 downto 0);
      cfg_err_locked_n           : out std_logic;
      cfg_err_cpl_rdy_n          : in  std_logic;
      cfg_trn_pending_n          : out std_logic;
      fast_train_simulation_only : out std_logic;
      trn_terrfwd_n              : out std_logic;
      b1_w32_w                   : out std_logic;
      b1_w32_be                  : out std_logic_vector(3 downto 0);
      b1_w32_d                   : out std_logic_vector(31 downto 0);
      b1_w32_a                   : out std_logic_vector(31 downto 0);
      b1_r32_r                   : out std_logic;
      b1_r32_be                  : out std_logic_vector(3 downto 0);
      b1_r32_a                   : out std_logic_vector(31 downto 0);
      b1_r32_q                   : in  std_logic_vector(31 downto 0);
      sim_error                  : in  std_logic;
      sw_reset_n                 : out std_logic;
      record_en                  : out std_logic;
      play_en                    : out std_logic;
      sim_en                     : out std_logic;
      fifo_wrreq_pcie_us         : in  std_logic;
      fifo_data_pcie_us          : in  std_logic_vector(63 downto 0);
      fifo_prog_full_pcie_us     : out std_logic;
      fifo_rdreq_pcie_ds         : in  std_logic;
      fifo_q_pcie_ds             : out std_logic_vector(63 downto 0);
      fifo_empty_pcie_ds         : out std_logic
      );
  end component;


  signal trn_tsof_n     : std_logic;
  signal trn_teof_n     : std_logic;
  signal trn_tsrc_rdy_n : std_logic;
  signal trn_tdst_rdy_n : std_logic;
  signal trn_trem_n     : std_logic_vector(7 downto 0);
  signal trn_td         : std_logic_vector(63 downto 0);
  signal trn_tsrc_dsc_n : std_logic;
  signal trn_tdst_dsc_n : std_logic;
  signal trn_tbuf_av    : std_logic_vector(3 downto 0);

  signal trn_rsof_n           : std_logic;
  signal trn_reof_n           : std_logic;
  signal trn_rsrc_rdy_n       : std_logic;
  signal trn_rdst_rdy_n       : std_logic;
  signal trn_rrem_n           : std_logic_vector(7 downto 0);
  signal trn_rd               : std_logic_vector(63 downto 0);
  signal trn_rerrfwd_n        : std_logic;
  signal trn_rsrc_dsc_n       : std_logic;
  signal trn_rnp_ok_n         : std_logic;
  signal trn_rcpl_streaming_n : std_logic;
  signal trn_rbar_hit_n       : std_logic_vector(6 downto 0);
  signal trn_rfc_ph_av        : std_logic_vector(7 downto 0);
  signal trn_rfc_pd_av        : std_logic_vector(11 downto 0);
  signal trn_rfc_nph_av       : std_logic_vector(7 downto 0);
  signal trn_rfc_npd_av       : std_logic_vector(11 downto 0);

  signal cfg_wr_en_n           : std_logic;
  signal cfg_rd_en_n           : std_logic;
  signal cfg_rd_wr_done_n      : std_logic;
  signal cfg_byte_en_n         : std_logic_vector(3 downto 0);
  signal cfg_dwaddr            : std_logic_vector(9 downto 0);
  signal cfg_di                : std_logic_vector(31 downto 0);
  signal cfg_do                : std_logic_vector(31 downto 0);
  signal cfg_bus_number        : std_logic_vector(7 downto 0);
  signal cfg_device_number     : std_logic_vector(4 downto 0);
  signal cfg_function_number   : std_logic_vector(2 downto 0);
  signal cfg_status            : std_logic_vector(15 downto 0);
  signal cfg_command           : std_logic_vector(15 downto 0);
  signal cfg_dstatus           : std_logic_vector(15 downto 0);
  signal cfg_dcommand          : std_logic_vector(15 downto 0);
  signal cfg_lstatus           : std_logic_vector(15 downto 0);
  signal cfg_lcommand          : std_logic_vector(15 downto 0);
  signal cfg_dsn               : std_logic_vector(63 downto 0);
  signal cfg_pm_wake_n         : std_logic;
  signal cfg_pcie_link_state_n : std_logic_vector(2 downto 0);
  signal cfg_to_turnoff_n      : std_logic;

  signal cfg_interrupt_mmenable  : std_logic_vector(2 downto 0);
  signal cfg_interrupt_msienable : std_logic;
  signal cfg_interrupt_do        : std_logic_vector(7 downto 0);
  signal cfg_interrupt_n         : std_logic;
  signal cfg_interrupt_rdy_n     : std_logic;
  signal cfg_interrupt_di        : std_logic_vector(7 downto 0);
  signal cfg_interrupt_assert_n  : std_logic;

  signal cfg_err_ecrc_n         : std_logic;
  signal cfg_err_ur_n           : std_logic;
  signal cfg_err_cpl_timeout_n  : std_logic;
  signal cfg_err_cpl_unexpect_n : std_logic;
  signal cfg_err_cpl_abort_n    : std_logic;
  signal cfg_err_posted_n       : std_logic;
  signal cfg_err_cor_n          : std_logic;
  signal cfg_err_tlp_cpl_header : std_logic_vector(47 downto 0);
  signal cfg_err_locked_n       : std_logic;
  signal cfg_err_cpl_rdy_n      : std_logic;

  signal cfg_trn_pending_n : std_logic;

  signal fast_train_simulation_only : std_logic;
  signal trn_terrfwd_n              : std_logic;

  -- Declare intermediate signals for referenced outputs
  signal pcie_trn_clk_xhdl12          : std_logic;
  signal pcie_trn_reset_n_xhdl13      : std_logic;
  signal trn_lnk_up_n_xhdl18          : std_logic;
  signal pci_exp_txp_xhdl11           : std_logic_vector(3 downto 0);
  signal pci_exp_txn_xhdl10           : std_logic_vector(3 downto 0);
  signal b1_w32_w_xhdl6               : std_logic;
  signal b1_w32_be_xhdl4              : std_logic_vector(3 downto 0);
  signal b1_w32_d_xhdl5               : std_logic_vector(31 downto 0);
  signal b1_w32_a_xhdl3               : std_logic_vector(31 downto 0);
  signal b1_r32_r_xhdl2               : std_logic;
  signal b1_r32_be_xhdl1              : std_logic_vector(3 downto 0);
  signal b1_r32_a_xhdl0               : std_logic_vector(31 downto 0);
  signal sw_reset_n_xhdl17            : std_logic;
  signal record_en_xhdl15             : std_logic;
  signal play_en_xhdl14               : std_logic;
  signal sim_en_xhdl16                : std_logic;
  signal fifo_prog_full_pcie_us_xhdl8 : std_logic;
  signal fifo_q_pcie_ds_xhdl9         : std_logic_vector(63 downto 0);
  signal fifo_empty_pcie_ds_xhdl7     : std_logic;
begin
  -- Drive referenced outputs
  pcie_trn_clk           <= pcie_trn_clk_xhdl12;
  pcie_trn_reset_n       <= pcie_trn_reset_n_xhdl13;
  trn_lnk_up_n           <= trn_lnk_up_n_xhdl18;
  pci_exp_txp            <= pci_exp_txp_xhdl11;
  pci_exp_txn            <= pci_exp_txn_xhdl10;
  b1_w32_w               <= b1_w32_w_xhdl6;
  b1_w32_be              <= b1_w32_be_xhdl4;
  b1_w32_d               <= b1_w32_d_xhdl5;
  b1_w32_a               <= b1_w32_a_xhdl3;
  b1_r32_r               <= b1_r32_r_xhdl2;
  b1_r32_be              <= b1_r32_be_xhdl1;
  b1_r32_a               <= b1_r32_a_xhdl0;
  sw_reset_n             <= sw_reset_n_xhdl17;
  record_en              <= record_en_xhdl15;
  play_en                <= play_en_xhdl14;
  sim_en                 <= sim_en_xhdl16;
  fifo_prog_full_pcie_us <= fifo_prog_full_pcie_us_xhdl8;
  fifo_q_pcie_ds         <= fifo_q_pcie_ds_xhdl9;
  fifo_empty_pcie_ds     <= fifo_empty_pcie_ds_xhdl7;



  ep : endpoint_blk_plus_v1_13
    port map (
      sys_reset_n => perstn,
      sys_clk     => pcie_refclk,
      refclkout   => open,

      pci_exp_txp => pci_exp_txp_xhdl11,
      pci_exp_txn => pci_exp_txn_xhdl10,
      pci_exp_rxn => pci_exp_rxn,
      pci_exp_rxp => pci_exp_rxp,

      trn_clk      => pcie_trn_clk_xhdl12,
      trn_lnk_up_n => trn_lnk_up_n_xhdl18,
      trn_reset_n  => pcie_trn_reset_n_xhdl13,

      trn_tsof_n     => trn_tsof_n,
      trn_teof_n     => trn_teof_n,
      trn_tsrc_rdy_n => trn_tsrc_rdy_n,
      trn_tdst_rdy_n => trn_tdst_rdy_n,
      trn_trem_n     => trn_trem_n,
      trn_td         => trn_td,
      trn_tsrc_dsc_n => trn_tsrc_dsc_n,
      trn_tdst_dsc_n => trn_tdst_dsc_n,
      trn_tbuf_av    => trn_tbuf_av,

      trn_rsof_n           => trn_rsof_n,
      trn_reof_n           => trn_reof_n,
      trn_rsrc_rdy_n       => trn_rsrc_rdy_n,
      trn_rdst_rdy_n       => trn_rdst_rdy_n,
      trn_rrem_n           => trn_rrem_n,
      trn_rd               => trn_rd,
      trn_rerrfwd_n        => trn_rerrfwd_n,
      trn_rsrc_dsc_n       => trn_rsrc_dsc_n,
      trn_rnp_ok_n         => trn_rnp_ok_n,
      trn_rcpl_streaming_n => trn_rcpl_streaming_n,
      trn_rbar_hit_n       => trn_rbar_hit_n,
      trn_rfc_ph_av        => trn_rfc_ph_av,
      trn_rfc_pd_av        => trn_rfc_pd_av,
      trn_rfc_nph_av       => trn_rfc_nph_av,
      trn_rfc_npd_av       => trn_rfc_npd_av,

      cfg_wr_en_n           => cfg_wr_en_n,
      cfg_rd_en_n           => cfg_rd_en_n,
      cfg_rd_wr_done_n      => cfg_rd_wr_done_n,
      cfg_byte_en_n         => cfg_byte_en_n,
      cfg_dwaddr            => cfg_dwaddr,
      cfg_di                => cfg_di,
      cfg_do                => cfg_do,
      cfg_bus_number        => cfg_bus_number,
      cfg_device_number     => cfg_device_number,
      cfg_function_number   => cfg_function_number,
      cfg_status            => cfg_status,
      cfg_command           => cfg_command,
      cfg_dstatus           => cfg_dstatus,
      cfg_dcommand          => cfg_dcommand,
      cfg_lstatus           => cfg_lstatus,
      cfg_lcommand          => cfg_lcommand,
      cfg_dsn               => cfg_dsn,
      cfg_pm_wake_n         => cfg_pm_wake_n,
      cfg_pcie_link_state_n => cfg_pcie_link_state_n,
      cfg_to_turnoff_n      => cfg_to_turnoff_n,

      cfg_interrupt_mmenable  => cfg_interrupt_mmenable,
      cfg_interrupt_msienable => cfg_interrupt_msienable,
      cfg_interrupt_do        => cfg_interrupt_do,
      cfg_interrupt_n         => cfg_interrupt_n,
      cfg_interrupt_rdy_n     => cfg_interrupt_rdy_n,
      cfg_interrupt_di        => cfg_interrupt_di,
      cfg_interrupt_assert_n  => cfg_interrupt_assert_n,

      cfg_err_ecrc_n         => cfg_err_ecrc_n,
      cfg_err_ur_n           => cfg_err_ur_n,
      cfg_err_cpl_timeout_n  => cfg_err_cpl_timeout_n,
      cfg_err_cpl_unexpect_n => cfg_err_cpl_unexpect_n,
      cfg_err_cpl_abort_n    => cfg_err_cpl_abort_n,
      cfg_err_posted_n       => cfg_err_posted_n,
      cfg_err_cor_n          => cfg_err_cor_n,
      cfg_err_tlp_cpl_header => cfg_err_tlp_cpl_header,
      cfg_err_locked_n       => cfg_err_locked_n,
      cfg_err_cpl_rdy_n      => cfg_err_cpl_rdy_n,

      cfg_trn_pending_n => cfg_trn_pending_n,

      fast_train_simulation_only => fast_train_simulation_only,
      trn_terrfwd_n              => trn_terrfwd_n
      );



  pcie_dma_wrapper_inst : pcie_dma_wrapper
    generic map (
      tDLY => tDLY
      )
    port map (
      trn_clk      => pcie_trn_clk_xhdl12,
      pcie_us_clk  => pcie_us_clk,
      pcie_ds_clk  => pcie_ds_clk,
      trn_reset_n  => pcie_trn_reset_n_xhdl13,
      trn_lnk_up_n => trn_lnk_up_n_xhdl18,
      sys_reset_n  => sys_reset_n,

      trn_tsof_n     => trn_tsof_n,
      trn_teof_n     => trn_teof_n,
      trn_tsrc_rdy_n => trn_tsrc_rdy_n,
      trn_tdst_rdy_n => trn_tdst_rdy_n,
      trn_trem_n     => trn_trem_n,
      trn_td         => trn_td,
      trn_tsrc_dsc_n => trn_tsrc_dsc_n,
      trn_tdst_dsc_n => trn_tdst_dsc_n,
      trn_tbuf_av    => trn_tbuf_av,

      trn_rsof_n           => trn_rsof_n,
      trn_reof_n           => trn_reof_n,
      trn_rsrc_rdy_n       => trn_rsrc_rdy_n,
      trn_rdst_rdy_n       => trn_rdst_rdy_n,
      trn_rrem_n           => trn_rrem_n,
      trn_rd               => trn_rd,
      trn_rerrfwd_n        => trn_rerrfwd_n,
      trn_rsrc_dsc_n       => trn_rsrc_dsc_n,
      trn_rnp_ok_n         => trn_rnp_ok_n,
      trn_rcpl_streaming_n => trn_rcpl_streaming_n,
      trn_rbar_hit_n       => trn_rbar_hit_n,
      trn_rfc_ph_av        => trn_rfc_ph_av,
      trn_rfc_pd_av        => trn_rfc_pd_av,
      trn_rfc_nph_av       => trn_rfc_nph_av,
      trn_rfc_npd_av       => trn_rfc_npd_av,

      cfg_wr_en_n           => cfg_wr_en_n,
      cfg_rd_en_n           => cfg_rd_en_n,
      cfg_rd_wr_done_n      => cfg_rd_wr_done_n,
      cfg_byte_en_n         => cfg_byte_en_n,
      cfg_dwaddr            => cfg_dwaddr,
      cfg_di                => cfg_di,
      cfg_do                => cfg_do,
      cfg_bus_number        => cfg_bus_number,
      cfg_device_number     => cfg_device_number,
      cfg_function_number   => cfg_function_number,
      cfg_status            => cfg_status,
      cfg_command           => cfg_command,
      cfg_dstatus           => cfg_dstatus,
      cfg_dcommand          => cfg_dcommand,
      cfg_lstatus           => cfg_lstatus,
      cfg_lcommand          => cfg_lcommand,
      cfg_dsn               => cfg_dsn,
      cfg_pm_wake_n         => cfg_pm_wake_n,
      cfg_pcie_link_state_n => cfg_pcie_link_state_n,
      cfg_to_turnoff_n      => cfg_to_turnoff_n,

      cfg_interrupt_mmenable  => cfg_interrupt_mmenable,
      cfg_interrupt_msienable => cfg_interrupt_msienable,
      cfg_interrupt_do        => cfg_interrupt_do,
      cfg_interrupt_n         => cfg_interrupt_n,
      cfg_interrupt_rdy_n     => cfg_interrupt_rdy_n,
      cfg_interrupt_di        => cfg_interrupt_di,
      cfg_interrupt_assert_n  => cfg_interrupt_assert_n,

      cfg_err_ecrc_n         => cfg_err_ecrc_n,
      cfg_err_ur_n           => cfg_err_ur_n,
      cfg_err_cpl_timeout_n  => cfg_err_cpl_timeout_n,
      cfg_err_cpl_unexpect_n => cfg_err_cpl_unexpect_n,
      cfg_err_cpl_abort_n    => cfg_err_cpl_abort_n,
      cfg_err_posted_n       => cfg_err_posted_n,
      cfg_err_cor_n          => cfg_err_cor_n,
      cfg_err_tlp_cpl_header => cfg_err_tlp_cpl_header,
      cfg_err_locked_n       => cfg_err_locked_n,
      cfg_err_cpl_rdy_n      => cfg_err_cpl_rdy_n,

      cfg_trn_pending_n => cfg_trn_pending_n,

      fast_train_simulation_only => fast_train_simulation_only,
      trn_terrfwd_n              => trn_terrfwd_n,

      b1_w32_w  => b1_w32_w_xhdl6,
      b1_w32_be => b1_w32_be_xhdl4,
      b1_w32_d  => b1_w32_d_xhdl5,
      b1_w32_a  => b1_w32_a_xhdl3,
      b1_r32_r  => b1_r32_r_xhdl2,
      b1_r32_be => b1_r32_be_xhdl1,
      b1_r32_a  => b1_r32_a_xhdl0,
      b1_r32_q  => b1_r32_q,

      sim_error => sim_error,

      sw_reset_n => sw_reset_n_xhdl17,

      record_en => record_en_xhdl15,
      play_en   => play_en_xhdl14,
      sim_en    => sim_en_xhdl16,

      fifo_wrreq_pcie_us     => fifo_wrreq_pcie_us,
      fifo_data_pcie_us      => fifo_data_pcie_us,
      fifo_prog_full_pcie_us => fifo_prog_full_pcie_us_xhdl8,

      fifo_rdreq_pcie_ds => fifo_rdreq_pcie_ds,
      fifo_q_pcie_ds     => fifo_q_pcie_ds_xhdl9,
      fifo_empty_pcie_ds => fifo_empty_pcie_ds_xhdl7
      );

end architecture trans;







