----------------------------------------------------------------------------------------------
--
-- Generated by X-HDL Verilog Translator - Version 2.0.0 Feb. 1, 2011
-- ?? ??? 28 2014 09:38:01
--
--      Input file      : 
--      Component name  : pcie_dma_wrapper
--      Author          : 
--      Company         : 
--
--      Description     : 
--
--
----------------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;


entity pcie_dma_wrapper is
  generic (
    tDLY : integer := 0
    );
  port (

    trn_clk      : in std_logic;
    pcie_us_clk  : in std_logic;
    pcie_ds_clk  : in std_logic;
    trn_reset_n  : in std_logic;
    trn_lnk_up_n : in std_logic;
    sys_reset_n  : in std_logic;

    trn_tsof_n     : out std_logic;
    trn_teof_n     : out std_logic;
    trn_tsrc_rdy_n : out std_logic;
    trn_tdst_rdy_n : in  std_logic;
    trn_trem_n     : out std_logic_vector(7 downto 0);
    trn_td         : out std_logic_vector(63 downto 0);
    trn_tsrc_dsc_n : out std_logic;
    trn_tdst_dsc_n : in  std_logic;
    trn_tbuf_av    : in  std_logic_vector(3 downto 0);

    trn_rsof_n           : in  std_logic;
    trn_reof_n           : in  std_logic;
    trn_rsrc_rdy_n       : in  std_logic;
    trn_rdst_rdy_n       : out std_logic;
    trn_rrem_n           : in  std_logic_vector(7 downto 0);
    trn_rd               : in  std_logic_vector(63 downto 0);
    trn_rerrfwd_n        : in  std_logic;
    trn_rsrc_dsc_n       : in  std_logic;
    trn_rnp_ok_n         : out std_logic;
    trn_rcpl_streaming_n : out std_logic;
    trn_rbar_hit_n       : in  std_logic_vector(6 downto 0);
    trn_rfc_ph_av        : in  std_logic_vector(7 downto 0);
    trn_rfc_pd_av        : in  std_logic_vector(11 downto 0);
    trn_rfc_nph_av       : in  std_logic_vector(7 downto 0);
    trn_rfc_npd_av       : in  std_logic_vector(11 downto 0);

    cfg_wr_en_n           : out std_logic;
    cfg_rd_en_n           : out std_logic;
    cfg_rd_wr_done_n      : in  std_logic;
    cfg_byte_en_n         : out std_logic_vector(3 downto 0);
    cfg_dwaddr            : out std_logic_vector(9 downto 0);
    cfg_di                : out std_logic_vector(31 downto 0);
    cfg_do                : in  std_logic_vector(31 downto 0);
    cfg_bus_number        : in  std_logic_vector(7 downto 0);
    cfg_device_number     : in  std_logic_vector(4 downto 0);
    cfg_function_number   : in  std_logic_vector(2 downto 0);
    cfg_status            : in  std_logic_vector(15 downto 0);
    cfg_command           : in  std_logic_vector(15 downto 0);
    cfg_dstatus           : in  std_logic_vector(15 downto 0);
    cfg_dcommand          : in  std_logic_vector(15 downto 0);
    cfg_lstatus           : in  std_logic_vector(15 downto 0);
    cfg_lcommand          : in  std_logic_vector(15 downto 0);
    cfg_dsn               : out std_logic_vector(63 downto 0);
    cfg_pm_wake_n         : out std_logic;
    cfg_pcie_link_state_n : in  std_logic_vector(2 downto 0);
    cfg_to_turnoff_n      : in  std_logic;

    cfg_interrupt_mmenable  : in  std_logic_vector(2 downto 0);
    cfg_interrupt_msienable : in  std_logic;
    cfg_interrupt_do        : in  std_logic_vector(7 downto 0);
    cfg_interrupt_n         : out std_logic;
    cfg_interrupt_rdy_n     : in  std_logic;
    cfg_interrupt_di        : out std_logic_vector(7 downto 0);
    cfg_interrupt_assert_n  : out std_logic;

    cfg_err_ecrc_n         : out std_logic;
    cfg_err_ur_n           : out std_logic;
    cfg_err_cpl_timeout_n  : out std_logic;
    cfg_err_cpl_unexpect_n : out std_logic;
    cfg_err_cpl_abort_n    : out std_logic;
    cfg_err_posted_n       : out std_logic;
    cfg_err_cor_n          : out std_logic;
    cfg_err_tlp_cpl_header : out std_logic_vector(47 downto 0);
    cfg_err_locked_n       : out std_logic;
    cfg_err_cpl_rdy_n      : in  std_logic;

    cfg_trn_pending_n : out std_logic;

    fast_train_simulation_only : out std_logic;
    trn_terrfwd_n              : out std_logic;

    b1_w32_w  : out std_logic;
    b1_w32_be : out std_logic_vector(3 downto 0);
    b1_w32_d  : out std_logic_vector(31 downto 0);
    b1_w32_a  : out std_logic_vector(31 downto 0);
    b1_r32_r  : out std_logic;
    b1_r32_be : out std_logic_vector(3 downto 0);
    b1_r32_a  : out std_logic_vector(31 downto 0);
    b1_r32_q  : in  std_logic_vector(31 downto 0);

    sim_error : in std_logic;

    sw_reset_n : out std_logic;

    record_en : out std_logic;
    play_en   : out std_logic;
    sim_en    : out std_logic;

    fifo_wrreq_pcie_us     : in  std_logic;
    fifo_data_pcie_us      : in  std_logic_vector(63 downto 0);
    fifo_prog_full_pcie_us : out std_logic;

    fifo_rdreq_pcie_ds : in  std_logic;
    fifo_q_pcie_ds     : out std_logic_vector(63 downto 0);
    fifo_empty_pcie_ds : out std_logic
    );
end entity pcie_dma_wrapper;

architecture trans of pcie_dma_wrapper is
  
  signal dmawas         : std_logic_vector(31 downto 0);
  signal dmawad_l       : std_logic_vector(31 downto 0);
  signal dmawad_u       : std_logic_vector(31 downto 0);
  signal dmaras_l       : std_logic_vector(31 downto 0);
  signal dmaras_u       : std_logic_vector(31 downto 0);
  signal dmarad         : std_logic_vector(31 downto 0);
  signal dmawxs         : std_logic_vector(31 downto 0);
  signal dmarxs         : std_logic_vector(31 downto 0);
  signal lpci_intm      : std_logic_vector(31 downto 0);
  signal lpci_ints      : std_logic_vector(31 downto 0);
  signal dma_wabt_rq    : std_logic;
  signal dma_wabt_ack   : std_logic;
  signal dma_rabt_rq    : std_logic;
  signal dma_rabt_ack_0 : std_logic;
  signal dma_rabt_ack_1 : std_logic;

  signal dma_ws : std_logic;
  signal dma_rs : std_logic;
  signal dma_wd : std_logic;
  signal dma_rd : std_logic;

  signal b0_w32_w    : std_logic;
  signal b0_w32_be   : std_logic_vector(3 downto 0);
  signal b0_w32_d    : std_logic_vector(31 downto 0);
  signal b0_w32_a    : std_logic_vector(31 downto 0);
  signal b0_r32_tc   : std_logic_vector(2 downto 0);
  signal b0_r32_at   : std_logic_vector(1 downto 0);
  signal b0_r32_rqid : std_logic_vector(15 downto 0);
  signal b0_r32_tg   : std_logic_vector(7 downto 0);
  signal b0_r32_r    : std_logic;
  signal b0_r32_be   : std_logic_vector(3 downto 0);
  signal b0_r32_a    : std_logic_vector(31 downto 0);
  signal b0_r32_q    : std_logic_vector(31 downto 0);

  signal b1_r32_tc   : std_logic_vector(2 downto 0);
  signal b1_r32_at   : std_logic_vector(1 downto 0);
  signal b1_r32_rqid : std_logic_vector(15 downto 0);
  signal b1_r32_tg   : std_logic_vector(7 downto 0);

  signal fifo_wrreq_pcie_ds     : std_logic;
  signal fifo_data_pcie_ds      : std_logic_vector(63 downto 0);
  signal fifo_prog_full_pcie_ds : std_logic;

  signal b0_cpld_rq  : std_logic;
  signal b0_cpld_ack : std_logic;

  signal b1_cpld_rq  : std_logic;
  signal b1_cpld_ack : std_logic;

  signal dmawtlp_sz  : std_logic_vector(10 downto 0);
  signal dmawtlp_num : std_logic_vector(24 downto 0);

  signal dmartlp_sz  : std_logic_vector(10 downto 0);
  signal dmartlp_num : std_logic_vector(24 downto 0);

  signal fifo_rst_pcie_us   : std_logic;
  signal fifo_rdreq_pcie_us : std_logic;
  signal fifo_q_pcie_us     : std_logic_vector(63 downto 0);
  signal fifo_empty_pcie_us : std_logic;
  signal fifo_dcnt_pcie_us  : std_logic_vector(9 downto 0);

  -- Declare intermediate signals for referenced outputs
  signal trn_tsof_n_xhdl38             : std_logic;
  signal trn_teof_n_xhdl36             : std_logic;
  signal trn_tsrc_rdy_n_xhdl40         : std_logic;
  signal trn_trem_n_xhdl37             : std_logic_vector(7 downto 0);
  signal trn_td_xhdl35                 : std_logic_vector(63 downto 0);
  signal trn_tsrc_dsc_n_xhdl39         : std_logic;
  signal trn_rdst_rdy_n_xhdl33         : std_logic;
  signal trn_rnp_ok_n_xhdl34           : std_logic;
  signal trn_rcpl_streaming_n_xhdl32   : std_logic;
  signal cfg_wr_en_n_xhdl24            : std_logic;
  signal cfg_rd_en_n_xhdl23            : std_logic;
  signal cfg_byte_en_n_xhdl7           : std_logic_vector(3 downto 0);
  signal cfg_dwaddr_xhdl9              : std_logic_vector(9 downto 0);
  signal cfg_di_xhdl8                  : std_logic_vector(31 downto 0);
  signal cfg_pm_wake_n_xhdl22          : std_logic;
  signal cfg_interrupt_n_xhdl21        : std_logic;
  signal cfg_interrupt_di_xhdl20       : std_logic_vector(7 downto 0);
  signal cfg_interrupt_assert_n_xhdl19 : std_logic;
  signal cfg_err_ecrc_n_xhdl14         : std_logic;
  signal cfg_err_ur_n_xhdl18           : std_logic;
  signal cfg_err_cpl_timeout_n_xhdl12  : std_logic;
  signal cfg_err_cpl_unexpect_n_xhdl13 : std_logic;
  signal cfg_err_cpl_abort_n_xhdl11    : std_logic;
  signal cfg_err_posted_n_xhdl16       : std_logic;
  signal cfg_err_cor_n_xhdl10          : std_logic;
  signal cfg_err_tlp_cpl_header_xhdl17 : std_logic_vector(47 downto 0);
  signal cfg_err_locked_n_xhdl15       : std_logic;
  signal b1_w32_w_xhdl6                : std_logic;
  signal b1_w32_be_xhdl4               : std_logic_vector(3 downto 0);
  signal b1_w32_d_xhdl5                : std_logic_vector(31 downto 0);
  signal b1_w32_a_xhdl3                : std_logic_vector(31 downto 0);
  signal b1_r32_r_xhdl2                : std_logic;
  signal b1_r32_be_xhdl1               : std_logic_vector(3 downto 0);
  signal b1_r32_a_xhdl0                : std_logic_vector(31 downto 0);
  signal sw_reset_n_xhdl31             : std_logic;
  signal record_en_xhdl29              : std_logic;
  signal play_en_xhdl28                : std_logic;
  signal sim_en_xhdl30                 : std_logic;
  signal fifo_prog_full_pcie_us_xhdl26 : std_logic;
  signal fifo_q_pcie_ds_xhdl27         : std_logic_vector(63 downto 0);
  signal fifo_empty_pcie_ds_xhdl25     : std_logic;
begin
  -- Drive referenced outputs
  trn_tsof_n             <= trn_tsof_n_xhdl38;
  trn_teof_n             <= trn_teof_n_xhdl36;
  trn_tsrc_rdy_n         <= trn_tsrc_rdy_n_xhdl40;
  trn_trem_n             <= trn_trem_n_xhdl37;
  trn_td                 <= trn_td_xhdl35;
  trn_tsrc_dsc_n         <= trn_tsrc_dsc_n_xhdl39;
  trn_rdst_rdy_n         <= trn_rdst_rdy_n_xhdl33;
  trn_rnp_ok_n           <= trn_rnp_ok_n_xhdl34;
  trn_rcpl_streaming_n   <= trn_rcpl_streaming_n_xhdl32;
  cfg_wr_en_n            <= cfg_wr_en_n_xhdl24;
  cfg_rd_en_n            <= cfg_rd_en_n_xhdl23;
  cfg_byte_en_n          <= cfg_byte_en_n_xhdl7;
  cfg_dwaddr             <= cfg_dwaddr_xhdl9;
  cfg_di                 <= cfg_di_xhdl8;
  cfg_pm_wake_n          <= cfg_pm_wake_n_xhdl22;
  cfg_interrupt_n        <= cfg_interrupt_n_xhdl21;
  cfg_interrupt_di       <= cfg_interrupt_di_xhdl20;
  cfg_interrupt_assert_n <= cfg_interrupt_assert_n_xhdl19;
  cfg_err_ecrc_n         <= cfg_err_ecrc_n_xhdl14;
  cfg_err_ur_n           <= cfg_err_ur_n_xhdl18;
  cfg_err_cpl_timeout_n  <= cfg_err_cpl_timeout_n_xhdl12;
  cfg_err_cpl_unexpect_n <= cfg_err_cpl_unexpect_n_xhdl13;
  cfg_err_cpl_abort_n    <= cfg_err_cpl_abort_n_xhdl11;
  cfg_err_posted_n       <= cfg_err_posted_n_xhdl16;
  cfg_err_cor_n          <= cfg_err_cor_n_xhdl10;
  cfg_err_tlp_cpl_header <= cfg_err_tlp_cpl_header_xhdl17;
  cfg_err_locked_n       <= cfg_err_locked_n_xhdl15;
  b1_w32_w               <= b1_w32_w_xhdl6;
  b1_w32_be              <= b1_w32_be_xhdl4;
  b1_w32_d               <= b1_w32_d_xhdl5;
  b1_w32_a               <= b1_w32_a_xhdl3;
  b1_r32_r               <= b1_r32_r_xhdl2;
  b1_r32_be              <= b1_r32_be_xhdl1;
  b1_r32_a               <= b1_r32_a_xhdl0;
  sw_reset_n             <= sw_reset_n_xhdl31;
  record_en              <= record_en_xhdl29;
  play_en                <= play_en_xhdl28;
  sim_en                 <= sim_en_xhdl30;
  fifo_prog_full_pcie_us <= fifo_prog_full_pcie_us_xhdl26;
  fifo_q_pcie_ds         <= fifo_q_pcie_ds_xhdl27;
  fifo_empty_pcie_ds     <= fifo_empty_pcie_ds_xhdl25;

  fifo_rst_pcie_us <= to_stdlogic((not(sys_reset_n)) or (not(record_en_xhdl29))) after (tDLY)*1 ns;

  fast_train_simulation_only <= '0' after (tDLY)*1 ns;
  trn_terrfwd_n              <= '1' after (tDLY)*1 ns;

  cfg_trn_pending_n <= '1' after (tDLY)*1 ns;

  cfg_dsn <= "0000000100100011010001010110011110001001101010111100110111101111" after (tDLY)*1 ns;



  rx_trn_fsm_inst : rx_trn_fsm
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => trn_reset_n,

      trn_rsof_n           => trn_rsof_n,
      trn_reof_n           => trn_reof_n,
      trn_rsrc_rdy_n       => trn_rsrc_rdy_n,
      trn_rdst_rdy_n       => trn_rdst_rdy_n_xhdl33,
      trn_rrem_n           => trn_rrem_n,
      trn_rd               => trn_rd,
      trn_rerrfwd_n        => trn_rerrfwd_n,
      trn_rsrc_dsc_n       => trn_rsrc_dsc_n,
      trn_rnp_ok_n         => trn_rnp_ok_n_xhdl34,
      trn_rcpl_streaming_n => trn_rcpl_streaming_n_xhdl32,
      trn_rbar_hit_n       => trn_rbar_hit_n,
      trn_rfc_ph_av        => trn_rfc_ph_av,
      trn_rfc_pd_av        => trn_rfc_pd_av,
      trn_rfc_nph_av       => trn_rfc_nph_av,
      trn_rfc_npd_av       => trn_rfc_npd_av,

      dmarxs       => dmarxs,
      dma_rabt_rq  => dma_rabt_rq,
      dma_rabt_ack => dma_rabt_ack_1,
      dma_rs       => dma_rs,
      dma_rd       => dma_rd,

      b0_w32_w    => b0_w32_w,
      b0_w32_be   => b0_w32_be,
      b0_w32_d    => b0_w32_d,
      b0_w32_a    => b0_w32_a,
      b0_r32_tc   => b0_r32_tc,
      b0_r32_at   => b0_r32_at,
      b0_r32_rqid => b0_r32_rqid,
      b0_r32_tg   => b0_r32_tg,
      b0_r32_r    => b0_r32_r,
      b0_r32_be   => b0_r32_be,
      b0_r32_a    => b0_r32_a,

      b1_w32_w    => b1_w32_w_xhdl6,
      b1_w32_be   => b1_w32_be_xhdl4,
      b1_w32_d    => b1_w32_d_xhdl5,
      b1_w32_a    => b1_w32_a_xhdl3,
      b1_r32_tc   => b1_r32_tc,
      b1_r32_at   => b1_r32_at,
      b1_r32_rqid => b1_r32_rqid,
      b1_r32_tg   => b1_r32_tg,
      b1_r32_r    => b1_r32_r_xhdl2,
      b1_r32_be   => b1_r32_be_xhdl1,
      b1_r32_a    => b1_r32_a_xhdl0,

      fifo_wrreq_pcie_ds => fifo_wrreq_pcie_ds,
      fifo_data_pcie_ds  => fifo_data_pcie_ds,

      b0_cpld_rq  => b0_cpld_rq,
      b0_cpld_ack => b0_cpld_ack,

      b1_cpld_rq  => b1_cpld_rq,
      b1_cpld_ack => b1_cpld_ack
      );



  pcie_ds_buf_inst : pcie_ds_buf
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      pcie_ds_clk => pcie_ds_clk,
      trn_clk     => trn_clk,
      trn_reset_n => sys_reset_n,

      fifo_wrreq_pcie_ds     => fifo_wrreq_pcie_ds,
      fifo_data_pcie_ds      => fifo_data_pcie_ds,
      fifo_rdreq_pcie_ds     => fifo_rdreq_pcie_ds,
      fifo_q_pcie_ds         => fifo_q_pcie_ds_xhdl27,
      fifo_empty_pcie_ds     => fifo_empty_pcie_ds_xhdl25,
      fifo_prog_full_pcie_ds => fifo_prog_full_pcie_ds
      );



  dma_reg_file_inst : dma_reg_file
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_reset_n  => trn_reset_n,
      trn_lnk_up_n => trn_lnk_up_n,
      sys_reset_n  => sys_reset_n,

      cfg_link_speed          => cfg_lstatus(3 downto 0),
      cfg_link_width          => cfg_lstatus(9 downto 4),
      cfg_common_clock        => cfg_lstatus(12),
      cfg_io_space_en         => cfg_command(0),
      cfg_mem_space_en        => cfg_command(1),
      cfg_bus_master_en       => cfg_command(2),
      cfg_intr_dis            => cfg_command(10),
      cfg_pcie_link_state_n   => cfg_pcie_link_state_n,
      cfg_interrupt_msienable => cfg_interrupt_msienable,
      cfg_interrupt_mmenable  => cfg_interrupt_mmenable,
      cfg_max_payload_size    => cfg_dcommand(7 downto 5),
      cfg_max_read_req_size   => cfg_dcommand(14 downto 12),
      cfg_relaxed_ordering_en => cfg_dcommand(4),
      cfg_extended_tag_en     => cfg_dcommand(8),
      cfg_aspm_ctrl           => cfg_lcommand(1 downto 0),

      b0_w32_w  => b0_w32_w,
      b0_w32_be => b0_w32_be,
      b0_w32_a  => b0_w32_a,
      b0_w32_d  => b0_w32_d,
      b0_r32_r  => b0_r32_r,
      b0_r32_be => b0_r32_be,
      b0_r32_a  => b0_r32_a,
      b0_r32_q  => b0_r32_q,

      sim_error              => sim_error,
      fifo_prog_full_pcie_ds => fifo_prog_full_pcie_ds,

      sw_reset_n => sw_reset_n_xhdl31,

      record_en => record_en_xhdl29,
      play_en   => play_en_xhdl28,
      sim_en    => sim_en_xhdl30,

      dmawas            => dmawas,
      dmawad_l          => dmawad_l,
      dmawad_u          => dmawad_u,
      dmaras_l          => dmaras_l,
      dmaras_u          => dmaras_u,
      dmarad            => dmarad,
      dmawxs            => dmawxs,
      dmarxs            => dmarxs,
      lpci_intm         => lpci_intm,
      lpci_ints         => lpci_ints,
      dma_wabt_rq       => dma_wabt_rq,
      dma_wabt_ack      => dma_wabt_ack,
      dma_rabt_rq       => dma_rabt_rq,
      dma_rabt_ack_0    => dma_rabt_ack_0,
      dma_rabt_ack_1    => dma_rabt_ack_1,
      dma_ws            => dma_ws,
      dma_rs            => dma_rs,
      dma_wd            => dma_wd,
      dma_rd            => dma_rd,
      fifo_dcnt_pcie_us => fifo_dcnt_pcie_us
      );



  posted_pkt_slicer_inst : posted_pkt_slicer
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk     => trn_clk,
      trn_reset_n => trn_reset_n,

      dmawxs => dmawxs,

      max_pld_sz => cfg_dcommand(7 downto 5),

      dmawtlp_sz  => dmawtlp_sz,
      dmawtlp_num => dmawtlp_num
      );



  nonposted_pkt_slicer_inst : nonposted_pkt_slicer
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk     => trn_clk,
      trn_reset_n => trn_reset_n,

      dmarxs => dmarxs,

      max_rd_sz => cfg_dcommand(14 downto 12),

      dmartlp_sz  => dmartlp_sz,
      dmartlp_num => dmartlp_num
      );



  tx_trn_fsm_inst : tx_trn_fsm
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => trn_reset_n,

      dmawad_l     => dmawad_l,
      dmawad_u     => dmawad_u,
      dmaras_l     => dmaras_l,
      dmaras_u     => dmaras_u,
      dma_wabt_rq  => dma_wabt_rq,
      dma_wabt_ack => dma_wabt_ack,
      dma_rabt_rq  => dma_rabt_rq,
      dma_rabt_ack => dma_rabt_ack_0,
      dma_ws       => dma_ws,
      dma_wd       => dma_wd,
      dma_rs       => dma_rs,
      dma_rd       => dma_rd,

      dmawtlp_sz  => dmawtlp_sz,
      dmawtlp_num => dmawtlp_num,

      dmartlp_sz  => dmartlp_sz,
      dmartlp_num => dmartlp_num,

      cfg_bus_number          => cfg_bus_number,
      cfg_device_number       => cfg_device_number,
      cfg_function_number     => cfg_function_number,
      cfg_relaxed_ordering_en => cfg_dcommand(4),
      cfg_extended_tag_en     => cfg_dcommand(8),
      cfg_bus_master_en       => cfg_command(2),

      fifo_rdreq_pcie_us => fifo_rdreq_pcie_us,
      fifo_q_pcie_us     => fifo_q_pcie_us,
      fifo_empty_pcie_us => fifo_empty_pcie_us,

      b0_cpld_rq  => b0_cpld_rq,
      b0_cpld_ack => b0_cpld_ack,

      b0_r32_tc   => b0_r32_tc,
      b0_r32_at   => b0_r32_at,
      b0_r32_rqid => b0_r32_rqid,
      b0_r32_tg   => b0_r32_tg,
      b0_r32_be   => b0_r32_be,
      b0_r32_a    => b0_r32_a,
      b0_r32_q    => b0_r32_q,

      b1_cpld_rq  => b1_cpld_rq,
      b1_cpld_ack => b1_cpld_ack,

      b1_r32_tc   => b1_r32_tc,
      b1_r32_at   => b1_r32_at,
      b1_r32_rqid => b1_r32_rqid,
      b1_r32_tg   => b1_r32_tg,
      b1_r32_be   => b1_r32_be_xhdl1,
      b1_r32_a    => b1_r32_a_xhdl0,
      b1_r32_q    => b1_r32_q,

      trn_tsof_n     => trn_tsof_n_xhdl38,
      trn_teof_n     => trn_teof_n_xhdl36,
      trn_tsrc_rdy_n => trn_tsrc_rdy_n_xhdl40,
      trn_tdst_rdy_n => trn_tdst_rdy_n,
      trn_trem_n     => trn_trem_n_xhdl37,
      trn_td         => trn_td_xhdl35,
      trn_tsrc_dsc_n => trn_tsrc_dsc_n_xhdl39,
      trn_tdst_dsc_n => trn_tdst_dsc_n,
      trn_tbuf_av    => trn_tbuf_av
      );



  pcie_us_buf_inst : pcie_us_buf
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      pcie_us_clk      => pcie_us_clk,
      trn_clk          => trn_clk,
      trn_reset_n      => sys_reset_n,
      fifo_rst_pcie_us => fifo_rst_pcie_us,

      fifo_wrreq_pcie_us     => fifo_wrreq_pcie_us,
      fifo_data_pcie_us      => fifo_data_pcie_us,
      fifo_rdreq_pcie_us     => fifo_rdreq_pcie_us,
      fifo_q_pcie_us         => fifo_q_pcie_us,
      fifo_empty_pcie_us     => fifo_empty_pcie_us,
      fifo_prog_full_pcie_us => fifo_prog_full_pcie_us_xhdl26,
      fifo_dcnt_pcie_us      => fifo_dcnt_pcie_us
      );



  intr_ctrl_inst : intr_ctrl
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => sys_reset_n,

      cfg_intr_dis => cfg_command(10),

      lpci_intm => lpci_intm,
      lpci_ints => lpci_ints,
      dma_wd    => dma_wd,
      dma_rd    => dma_rd,

      cfg_interrupt_mmenable  => cfg_interrupt_mmenable,
      cfg_interrupt_msienable => cfg_interrupt_msienable,
      cfg_interrupt_do        => cfg_interrupt_do,
      cfg_interrupt_n         => cfg_interrupt_n_xhdl21,
      cfg_interrupt_rdy_n     => cfg_interrupt_rdy_n,
      cfg_interrupt_di        => cfg_interrupt_di_xhdl20,
      cfg_interrupt_assert_n  => cfg_interrupt_assert_n_xhdl19
      );



  cfg_inst : cfg
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => trn_reset_n,

      cfg_wr_en_n      => cfg_wr_en_n_xhdl24,
      cfg_rd_en_n      => cfg_rd_en_n_xhdl23,
      cfg_rd_wr_done_n => cfg_rd_wr_done_n,
      cfg_byte_en_n    => cfg_byte_en_n_xhdl7,
      cfg_dwaddr       => cfg_dwaddr_xhdl9,
      cfg_di           => cfg_di_xhdl8,
      cfg_do           => cfg_do
      );

  error_report_inst : error_report
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => trn_reset_n,

      cfg_err_ecrc_n         => cfg_err_ecrc_n_xhdl14,
      cfg_err_ur_n           => cfg_err_ur_n_xhdl18,
      cfg_err_cpl_timeout_n  => cfg_err_cpl_timeout_n_xhdl12,
      cfg_err_cpl_unexpect_n => cfg_err_cpl_unexpect_n_xhdl13,
      cfg_err_cpl_abort_n    => cfg_err_cpl_abort_n_xhdl11,
      cfg_err_posted_n       => cfg_err_posted_n_xhdl16,
      cfg_err_cor_n          => cfg_err_cor_n_xhdl10,
      cfg_err_tlp_cpl_header => cfg_err_tlp_cpl_header_xhdl17,
      cfg_err_locked_n       => cfg_err_locked_n_xhdl15,
      cfg_err_cpl_rdy_n      => cfg_err_cpl_rdy_n
      );

  pwr_mng_inst : pwr_mng
    generic map (
      tdly => to_stdlogic(tDLY)
      )
    port map (
      trn_clk      => trn_clk,
      trn_lnk_up_n => trn_lnk_up_n,
      trn_reset_n  => trn_reset_n,

      cfg_pm_wake_n         => cfg_pm_wake_n_xhdl22,
      cfg_pcie_link_state_n => cfg_pcie_link_state_n,
      cfg_to_turnoff_n      => cfg_to_turnoff_n
      );

end architecture trans;







